feat: 🎸 add suspend & unsuspend system token call
InfraBlockchain/infra-relay-chain pull request #63
Opened 2023-08-09 05:46 UTC by sweatpotato13

# Summary
- add `suspend_system_token` call
- add `unsuspend_system_token` call

# Describe Your Changes
```rust
                #[pallet::call_index(7)]
		#[pallet::weight(1_000)]
		// Description:
		// Suspend all `original` and `wrapped` system token registered on runtime.
		// Suspended system token is no longer used as `transaction fee`
		//
		// Origin:
		// ** Root(Authorized) privileged call **
		//
		// Params:
		// - original: Original system token id expected to be suspended
		pub fn suspend_system_token(
			origin: OriginFor<T>,
			original: SystemTokenId,
		) -> DispatchResult {
			ensure_root(origin)?;
			Self::try_suspend_all(original)?;
			Self::deposit_event(Event::<T>::OriginalSystemTokenSuspended { original });

			Ok(())
		}

		#[pallet::call_index(8)]
		#[pallet::weight(1_000)]
		// Description:
		// Unsuspend all `original` and `wrapped` system token registered on runtime.
		// Unsuspended system token is no longer used as `transaction fee`
		//
		// Origin:
		// ** Root(Authorized) privileged call **
		//
		// Params:
		// - original: Original system token id expected to be unsuspended
		pub fn unsuspend_system_token(
			origin: OriginFor<T>,
			original: SystemTokenId,
		) -> DispatchResult {
			ensure_root(origin)?;
			Self::try_unsuspend_all(original)?;
			Self::deposit_event(Event::<T>::OriginalSystemTokenUnsuspended { original });

			Ok(())
		}
```

- suspending system token is only set `is_sufficient` flag `false`, not remove related stored data or not unlink
- unsuspending system token is only set `is_sufficient` flag `true`

```rust
	fn try_suspend(wrapped: &SystemTokenId) -> DispatchResult {
		let original = OriginalSystemTokenConverter::<T>::get(&wrapped)
			.ok_or(Error::<T>::WrappedNotRegistered)?;

		let SystemTokenId { para_id, .. } = wrapped.clone();
		let property =
			SystemTokenProperties::<T>::get(original).ok_or(Error::<T>::PropertyNotFound)?;

		// Case: Original's self-wrapped
		if original.para_id == para_id {
			Self::try_set_sufficient_and_weight(&original, false, property.system_token_weight)?;
		} else {
			Self::try_set_sufficient_and_weight(&original, false, None)?;
		}

		Ok(())
	}

	fn try_unsuspend(wrapped: &SystemTokenId) -> DispatchResult {
		let original = OriginalSystemTokenConverter::<T>::get(&wrapped)
			.ok_or(Error::<T>::WrappedNotRegistered)?;

		let SystemTokenId { para_id, .. } = wrapped.clone();
		let property =
			SystemTokenProperties::<T>::get(original).ok_or(Error::<T>::PropertyNotFound)?;

		// Case: Original's self-wrapped
		if original.para_id == para_id {
			Self::try_set_sufficient_and_weight(&original, true, property.system_token_weight)?;
		} else {
			Self::try_set_sufficient_and_weight(&original, true, None)?;
		}

		Ok(())
	}
```

2023-08-09 06:06 UTC, cocoyoon commented on runtime/parachains/src/system_token_manager.rs
> +			Self::try_set_sufficient_and_weight(&original, false, property.system_token_weight)?;
`system_token_weight` 는 `try_set_sufficient_and_weight` parameter 맞추기 위함인가요?

2023-08-09 06:07 UTC, energyGiver requested changes
Do we need suspend/unsuspend calls for the wrapped_system_token, just like the original system token? I think we do, but I'm curious to hear your opinions.

2023-08-09 06:07 UTC, energyGiver commented on runtime/parachains/src/system_token_manager.rs
> +			Self::try_set_sufficient_and_weight(&original, true, None)?;
It seems that "None" should be replaced with property.system_token_weight.

2023-08-09 06:10 UTC, cocoyoon commented on runtime/parachains/src/system_token_manager.rs
> +			Self::try_set_sufficient_and_weight(&original, true, None)?;
모든 `wrapped` 에 대해서도 `sufficient` 상태를 변경해주는 것은 맞는 행위인거 같습니다

2023-08-09 06:10 UTC, sweatpotato13 commented on runtime/parachains/src/system_token_manager.rs
> +			Self::try_set_sufficient_and_weight(&original, false, property.system_token_weight)?;
네 기존과 동일한 값으로 유지하기 위함입니다.

2023-08-09 06:12 UTC, sweatpotato13 commented
> 

original 및 다른 wrapped를 두고 한 종류의 wrapped만 unsuspend 기능이 굳이 필요할지 모르겠습니다. 그 부분은 deregister wrapped system token이 충분히 그 기능을 수행해 줄 수 있을 것 같습니다.

2023-08-09 06:16 UTC, sweatpotato13 commented on runtime/parachains/src/system_token_manager.rs
> +			Self::try_set_sufficient_and_weight(&original, true, None)?;
wrapped의 SystemTokenProperties에서 `system_token_weight: None` 으로 들어가고 있어서 None으로 처리하는 줄 알았는데 실제로 Asset 생성할 때 제대로 들어가네요 이 부분은 수정 하겠습니다.

2023-08-09 06:17 UTC, cocoyoon commented
## Discussion

-  `suspend/unsuspend` 를 `(de)register` 하는 것처럼 `wrapped/original` 분리 시켜야할 거 같습니다
    - `(un)suspend(origin, system_token_type)`
    ```rust
    fn (un)suspend(origin, system_token_type) {
        match system_token_type {
            SystemTokenType::Original => { .. }
            SystemTokenType::Wrapped => { .. }    
        }
    }
    ```
-  `Asset Detail` 에 `suspend` flag 를 추가하는 것은 어떤가요?

2023-08-09 06:20 UTC, cocoyoon commented
> > Do we need suspend/unsuspend calls for the wrapped_system_token, just like the original system token? I think we do, but I'm curious to hear your opinions.
> 
> @energyGiver
> 
> original 및 다른 wrapped를 두고 한 종류의 wrapped만 unsuspend 기능이 굳이 필요할지 모르겠습니다. 그 부분은 deregister wrapped system token이 충분히 그 기능을 수행해 줄 수 있을 것 같습니다.

`DeregisterWrapped` 의 경우에도 Storage 를 변경하기 때문에 필요하지 않을까요

2023-08-09 06:29 UTC, sweatpotato13 commented
> > > Do we need suspend/unsuspend calls for the wrapped_system_token, just like the original system token? I think we do, but I'm curious to hear your opinions.
> > 
> > 
> > @energyGiver
> > original 및 다른 wrapped를 두고 한 종류의 wrapped만 unsuspend 기능이 굳이 필요할지 모르겠습니다. 그 부분은 deregister wrapped system token이 충분히 그 기능을 수행해 줄 수 있을 것 같습니다.
> 
> `DeregisterWrapped` 의 경우에도 Storage 를 변경하기 때문에 필요하지 않을까요

system token issuer가 직접적으로 본인이 원해서 original 혹은 wrapped token에 대해서 suspend 시킬 가능성은 거의 없고 정직하지 않은 행위로 인한 징벌적 개념으로 suspend 시킬 가능성이 크다고 보여지는데 그렇다면 더더욱 wrapped에 대한 suspend 혹은 unsuspend 기능은 필요하지 않을 것 같습니다.

해당 토큰에서 이상 행위가 보여지는 경우 특정 wrapped에 대해서만 처벌을 할 이유는 없고 original을 포함한 모든 wrapped를 한번에 suspend 시키는게 맞다고 보여집니다.

2023-08-09 06:39 UTC, cocoyoon commented on runtime/parachains/src/system_token_manager.rs
> +		pub fn unsuspend_system_token(
`Original` 에 대해서만 suspend 가 가능하다면은 `Suspend` Storage 를 둬서 해당 extrinsic 은 Suspend 인 토큰에 대해서만 호출할 수 있게 하는 것은 어떤가요?

```rust
pub type Suspend = StorageMap<SystemTokenId, Status>;
```

2023-08-09 06:40 UTC, cocoyoon commented on runtime/parachains/src/system_token_manager.rs
> +		pub fn unsuspend_system_token(
아니면 Inspect 쪽에 `suspend` 상태를 가져올 수 있는 메소드라던지

2023-08-09 06:50 UTC, sweatpotato13 commented on runtime/parachains/src/system_token_manager.rs
> +		pub fn unsuspend_system_token(
original에 대해서만 suspend가 가능한것이 아니고 original을 포함한 모든 wrapped를 한번에 처리합니다.

2023-08-09 06:56 UTC, cocoyoon commented on runtime/parachains/src/system_token_manager.rs
> +		pub fn unsuspend_system_token(
제 제안은 `Original` token 상태가 `suspend` 인지 아닌지 판단할 수 있는 상태를 저장하는 거였어요. 현재는 그 여부에 관계없이 호출이 되기 때문에 두는 것이 좋아보입니다. `suspend` 의 경우에도 `register` 상태일때만 호출되는 것이 좋아보이네요

```rust
// Possible status 
enum Status {
    Register,
    Suspend,
    Pending
}
```

2023-08-09 06:57 UTC, sweatpotato13 commented on runtime/parachains/src/system_token_manager.rs
> +		pub fn unsuspend_system_token(
Status의 경우는 확실히 필요해 보입니다. 명확한 상태를 보여주는 flag값은 있어야 할 것 같아요

2023-08-09 07:01 UTC, cocoyoon commented on runtime/parachains/src/system_token_manager.rs
> +		pub fn unsuspend_system_token(
이 상태를 `AssetDetail` 에 둘지 Storage 에 둘지는 의견 조율이 필요해보입니다. 개인적으로는 현 팔렛 스토리지로 두는 것이 좋아보입니다. 그리고 `Status` 는 어떤것이 있을지도 생각해봐야 하고요.

2023-08-09 07:07 UTC, sweatpotato13 commented on runtime/parachains/src/system_token_manager.rs
> +		pub fn unsuspend_system_token(
Status 종류는 현재로써는 Active, Suspend 이 두가지만 있어도 될 것 같네요

2023-08-09 07:10 UTC, sweatpotato13 commented on runtime/parachains/src/system_token_manager.rs
> +		pub fn unsuspend_system_token(
그리고 Token Status 상태를 굳이 파라체인별로 알 필요는 저도 없다고 생각해서 현 팔렛에 스토리지로 두는게 괜찮아 보이네요

2023-08-09 07:19 UTC, sweatpotato13 commented on runtime/parachains/src/system_token_manager.rs
> +		pub fn unsuspend_system_token(
`SystemTokenProperty` 에  추가로 두면 좋을거같은데요

2023-08-09 07:40 UTC, cocoyoon commented on runtime/parachains/src/system_token_manager.rs
> +		pub fn unsuspend_system_token(
이곳에 추가한다면 `Property` 를 변경하는 곳 잘 변경해주시고 이렇게 되면 등록하기 전 상태(`Default::default()`)도 필요해 보입니다.

2023-08-10 00:12 UTC, cocoyoon commented on runtime/parachains/src/system_token_manager.rs
> +		pub fn suspend_wrapped_system_token(
`wrapped` 에 대해서도 하기로 변경되었나요?

2023-08-10 00:48 UTC, sweatpotato13 commented on runtime/parachains/src/system_token_manager.rs
> +		pub fn suspend_wrapped_system_token(
deregister로 해결이 불가능한 케이스가 있을 것 같아 구현 해 두는것이 좋다고 판단 하였습니다.

2023-08-11 00:08 UTC, cocoyoon commented on runtime/parachains/src/system_token_manager.rs
> +	fn try_suspend(
`try_suspend` 호출은 해당 시스템 토큰이 `Active` 상태일때만 호출 가능하는게 어떤가요?

2023-08-11 00:13 UTC, cocoyoon commented on runtime/parachains/src/system_token_manager.rs
> +			*p = Some(property.clone());
`proporty` 소유권을 `p` 에 넘겨주기 때문에 `clone` 은 불필요해 보입니다

2023-08-14 00:08 UTC, cocoyoon commented on runtime/parachains/src/system_token_manager.rs
> +		Self::try_set_sufficient_and_weight(&original, false, property.system_token_weight)?;
제가 잘 이해했는지 모르겠지만 해당 코드가 `wrapped` 토큰의 상태를 변경하는게 맞나요? 
`Original` 의 토큰의 상태만 변경되는거 아닌가요?

2023-08-14 00:31 UTC, sweatpotato13 commented on runtime/parachains/src/system_token_manager.rs
> +		Self::try_set_sufficient_and_weight(&original, false, property.system_token_weight)?;
L822
```rust
Self::try_set_sufficient_and_weight(&wrapped, false, property.system_token_weight)?;
```
로 수정 되어야 하네요

L873 도 동일한 이유로 수정 하였습니다.

2023-08-14 01:33 UTC, cocoyoon approved these changes

2023-08-16 08:20 UTC, energyGiver approved these changes
👍

2023-08-16 08:21 UTC, merged